version: "2"
services:
  app:
    build: ./app
    links:
      - db
    ports:
      - "8889:5000"
  db:
    image: mysql
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro